services:

  mongodb-minibank:
    image: mongo
    restart: on-error
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD} # Ganti password dengan yang lebih aman.

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:minibank@mongo-minibank:27017/
      ME_CONFIG_BASICAUTH: false

